{% set name = "py7zr" %}
{% set version = "0.20.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d01f98ea1e1f5c49940358691b2076f9a5848056426541e783de33834f59e21

build:
  number: 0
  noarch: python
  entry_points:
    - py7zr = py7zr.__main__:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - python-build
    - setuptools >=63
    - setuptools-scm >=7.0.5
  run:
    - brotli-python >=1.0.9
    - brotlicffi >=1.0.9.2
    - importlib_metadata
    - inflate64 >=0.3.1
    - multivolumefile >=0.2.3
    - psutil
    - pybcj >=0.6.0
    - pybcpy
    - pycryptodomex >=3.6.6
    - pyppmd >=0.18.1,<1.1.0
    - python >=3.7
    - pyzstd >=0.14.4
    - texttable
    - zipfile-deflate64

test:
  imports:
    - py7zr
  commands:
    - py7zr --help

about:
  home: https://github.com/miurahr/py7zr
  summary: Pure python 7-zip library
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
